import { AssetModel } from "../assets/Asset.model";
import {IsNotEmpty, IsArray} from "class-validator";


export class MotherActivitiesModel {
  uid: string; //generated by mongoDB

  @IsNotEmpty()
  motherActivityId: string; //examples ActivityType.MessageFromChild:

  @IsNotEmpty()
  timePeriod: string; //example "D1" "W1" "M2"

  @IsArray()
  assets: AssetModel[] | string[];
}
