import { AssetInterface } from "../assets/Asset.interface";

export interface MotherActivitiesModel {
  uid: string; //generated by mongoDB
  motherActivityId: string; //examples ActivityType.MessageFromChild:
  timePeriod: string; //example "D1" "W1" "M2"

  assets: AssetInterface[] | string[];
}
